import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import pat from "../public/headshot-transparent-small.png";
import java from "../public/java-logo.png";
import csharp from "../public/csharp-logo.png";
import js from "../public/Javascript-logo.png";
import python from "../public/python-logo.png";
import sql from "../public/sql-logo.jpg";
import ts from "../public/typescript-logo.png";
import react from "../public/react-logo.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pat's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white-200 px-10">
        <section>
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-jetbrains">developed by Patrick</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600">Patrick Hastings</h2>
            <h3 className="text-2xl py-2">Software Engineer</h3>
            <p className="text-md">
              Creative thinker resolved to solve and produce solutions
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500  w-80 h-80 mt-20">
            <Image src={pat} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-center py-10 text-3xl">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Passionate about solving problems and creating value through
              technology, I blend 1.5+ years in Software Engineering with an
              8-year foundation in mortgage banking. This journey has equipped
              me with a unique perspective on adapting to change, innovating
              under pressure, and understanding user needs.
            </p>
          </div>
          <div>
            <div className="text-center">
              <h3 className="text-center p-10 text-lg font-medium pt-8 pb-5">
                Technologies
              </h3>
            </div>
            <div className="flex justify-center">
              <div
                className="grid grid-flow-row auto-rows-max justify-center gap-4 max-w-4xl mx-auto"
                style={{
                  gridTemplateColumns: "repeat(auto-fit, minmax(1px, 1fr))",
                }}
              >
                {[java, csharp, js, python, sql].map((src, index) => (
                  <div key={index} className="shadow-lg rounded-xl">
                    <div className="w-full h-full flex justify-center items-center">
                      <Image
                        src={src}
                        alt={`Icon ${index}`}
                        width={50} // This is now just for the Image component's aspect ratio
                        height={50}
                        objectFit="cover"
                        className="rounded-xl"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-center p-10 py-10 text-3xl">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              I have spent most of my time over the past year hard at work on
              internal Chase applications, which I cannot share. However, if you
              click on the languages above, I will be happy to explain the
              involvement of each and my future goals
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
