import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/headshot-transparent.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pat's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section>
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-jetbrains">developed by Patrick</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600">Patrick Hastings</h2>
            <h3 className="text-2xl py-2">Software Engineer</h3>
            <p className="text-md">
              Creative thinker resolved to solve and produce solutions
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="">
            <Image src={deved} alt="headshot2022bravodelta" />
          </div>
        </section>
      </main>
    </div>
  );
}
